django_blog/urls.py
from django.urls import path
from . views import PostListView, PostDetailView, PostUpdateView, PostCreateView, PostDeleteView, PostPublishView, PostChangeDateView, PostListByTagView
from . feeds import RssPostsFeed

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('tag/<int:pk>/', PostListByTagView.as_view(), name='list_by_tag'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('post/create/', PostCreateView.as_view(), name="create"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),
    path('post/<int:pk>/publish/', PostPublishView.as_view(), name="publish"),
    path('post/<int:pk>/change_date/', PostChangeDateView.as_view(), name="change_date"),
    path('feed/rss/', RssPostsFeed(), name="feed_rss")
]

django_blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog template</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
  </head>
  <body>
    <div class="container-xl py-4">
      {% if messages %}
        <!-- Display flash messages if present -->
        <div class="mt-4" id="messages">
          {% for message in messages %}<div class="alert alert-{{ message.tags }}">{{ message }}</div>{% endfor %}
        </div>
      {% endif %}
      {% block content %}
      {% endblock content %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
              integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
              crossorigin="anonymous"></script>
    </div>
  </body>
</html>

django_blog/templates/blog/feeds_description.html
{% if obj.subtitle %}
<p><strong>{{ obj.subtitle }}</strong></p>
{% endif %}
{{ obj.body | safe | truncatewords_html:50 }}

django_blog/templates/blog/post_change_date.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Programma pubblicazione </h1>
<form action="" method="post">
  {% crispy form %}
</form>
{% endblock content %}

django_blog/templates/blog/post_create.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Crea un nuovo post</h1>
{% crispy form %}

{{ post_tags | json_script:'post-tags' }}
{{ tags | json_script:'available-tags' }}
<script src="{% static 'blog/js/addtags.js' %}"></script>
<script src="static"></script>
{% endblock content %}

django_blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}
{% block content %}
<h1>Elimina post</h1>
<form action="" method="post">
  {% csrf_token %}
  <p>Confermi di voler eliminare il post <strong>{{ post }}</strong>?</p>
  <input type="submit" value="Conferma" class="btn btn-danger">
  <a href="{% url "blog:detail" post.pk %}" class="btn btn-outline-primary">Annulla</a>
</form>
{% endblock content %}

django_blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
  <h1>{{ post.title }}</h1>
  {% if post.subtitle %} <p>{{ post.subtitle }}</p>
{% endif %}
  <p>Author: {{ post.author }}</p>
  <p>Published: {{ post.pub_date }}, Updated: {{ post.update_date }}</p>
  {% if post.tags.all %}
  <ul>
    {% for tag in post.tags.all %}
    <li><a href="{% url "blog:list_by_tag" tag.pk %}">{{ tag }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  <div id="post-body">
    {{ post.body | safe }}
  </div>

  <div class="btn-group post_actions">
    {% if user.is_authenticated %}
      {% if not post.author or post.author == user %}
        <a href="{% url 'blog:update' post.pk %}" class="btn btn-light">
          Modifica
        </a>
        {% if not post.is_published %}
          <form action="{% url "blog:publish" post.pk %}" method="post" class="w-100">
            {% csrf_token %}
            <button type="submit" class="btn btn-light w-100">
              Pubblica
            </button>
          </form>
          <a href="{% url "blog:change_date" post.pk %}" class="btn btn-light">
            Programma
          </a>
        {% endif %}
        <a href="{% url 'blog:delete' post.pk %}" class="btn btn-danger">
          Elimina
        </a>
      {% endif %}
    {% endif %}
  </div>
{% endblock content %}

django_blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
  <h1>Blog</h1>
  {% if posts %}
    <ul>
      {% for post in posts %}
        <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    Non ci sono post
  {% endif %}
  {% if tags %}
    <h2>Tags</h2>
    <ul>
      {% for tag in tags %}
        <li>
          <a href="{% url "blog:list_by_tag" tag.pk %}">{{ tag }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous page</a></li>
      {% endif %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next page</a></li>
      {% endif %}
    </ul>
  {% endif %}
  {% if user.is_authenticated %}
    <a href="{% url 'blog:create' %}" class="btn btn-primary">Nuovo post</a>
  {% endif %}
{% endblock content %}

django_blog/templates/blog/post_list_by_tag.html
{% extends "blog/base.html" %}
{% block content %}
  <h1>Tag: {{ tag }}</h1>
  {% if posts %}
    <ul>
      {% for post in posts %}
        <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    Non ci sono post
  {% endif %}
  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous page</a>
        </li>
      {% endif %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next page</a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock content %}

django_blog/templates/blog/post_update.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Crea un nuovo post</h1>
{% crispy form %}

{{ post_tags | json_script:'post-tags' }}
{{ tags | json_script:'available-tags' }}
<script src="{% static 'blog/js/addtags.js' %}"></script>
<script src="static"></script>
{% endblock content %}